#!/usr/bin/env bash
cd $HOME/MASTER
install() {
rm -rf $HOME/.telegram-cli
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install software-properties-common -y
sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
sudo luaMASTERks install luasocket
sudo luaMASTERks install luasec
sudo luaMASTERks install redis-lua
sudo luaMASTERks install Lua-cURL
sudo service redis-server start
sudo apt-get update -y
sudo apt-get install g++-4.7 -y c++-4.7
sudo apt-get install libreadline-dev -y libconfig-dev -y libssl-dev -y lua5.2 -y liblua5.2-dev -y lua-socket -y lua-sec -y lua-expat -y libevent-dev -y make unzip git redis-server autoconf g++ -y libjansson-dev -y libpython-dev -y expat libexpat1-dev -y curl -y htop -y
sudo apt-get install screen -y
sudo apt-get install libstdc++6 -y
sudo apt-get install lua-lgi -y
sudo apt-get install libnotify-dev -y
sudo chmod +x tg
lua MASTER.lua
sudo chmod +x MASTER
sudo chmod +x ./MAS
./MAS
}
if [ "$1" = "install" ]; then
install
else
if [ ! -f ./tg ]; then
echo "Tg Is Not Found"
exit 1
fi
sudo chmod +x tg
lua MASTER.lua
sudo chmod +x MASTER
sudo chmod +x ./MAS
./MAS
fi
